apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app:1.0
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "password"
            - name: PGDATABASE
              value: "votes"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 3000
  selector:
    app: backend